kind: pipeline
name: default

steps:
  - name: build
    image: node:14  # Use a Node.js version compatible with your project
    commands:
      - npm install  # Install project dependencies (if you have any)
      - npm run build  # Replace with your build script or commands

